export const packages = [
  {
    ID: 1,
    Name: 'Classic Package ',
    Date: '1 July,2024',
    Price: '$50 - $999',
    PriceStart: 50,
    PriceEnd: 999,
    Currency: 'USD',
    Bonus: '100',
    Duration: 1,
    MonthlyReturn: '1 Year: 4%',
    MaturityBonus: 1,
  },
  {
    ID: 2,
    Name: 'GOLD pACKAGE',
    Date: '3 July,2024',
    Price: '$1000 - $4999',
    PriceStart: 1000,
    PriceEnd: 4999,
    Currency: 'USD',
    Bonus: '100',
    Duration: 1,
    MonthlyReturn: '1 Year: 7%',
    MaturityBonus: 2,
  },
];
